### ISSUE TITLE
[ 15%] Building CXX object CMakeFiles/vermilion.dir/lib/LoadShaders.cpp.o /home/wangwei/1编程指南-master/lib/LoadShaders.cpp: 在函数‘const GLchar* ReadShader(const char*)’中:

### ISSUE THREAD

**Issue by jackweiwang** [openglredbook/examples#1]
when I compile this code in linux  CENTOS7 
/home/wangwei/1编程指南-master/lib/LoadShaders.cpp:26:42: 错误：‘fopen’在此作用域中尚未声明
     FILE\* infile = fopen( filename, "rb" );
                                          ^
/home/wangwei/1编程指南-master/lib/LoadShaders.cpp:36:23: 错误：‘SEEK_END’在此作用域中尚未声明
     fseek( infile, 0, SEEK_END );
                       ^
/home/wangwei/1编程指南-master/lib/LoadShaders.cpp:36:32: 错误：‘fseek’在此作用域中尚未声明
     fseek( infile, 0, SEEK_END );

The title of error

**Comment by blob84** [comment]
Is it included <stdio.h> ?
