### ISSUE TITLE
How to build in ubuntu system?

### ISSUE THREAD

**Issue by songjiaxina** [openglredbook/examples#17]
Could anyone tell me how to build this project in ubuntu? Can I build in the traditional way as "mkdir build  cd build cmake .. make"? I did this .But a lot of errors happen.I don"t know why.

**Comment by nikolas** [comment]
What errors are you seeing? I've only been able to build these using elmindreda's branch here: https://github.com/openglredbook/examples/pull/5

**Comment by songjiaxina** [comment]
Thanks a lot. I have already solved this problem. Thanks!

nikolas <notifications@github.com> 于2018年9月2日周日 上午5:55写道：
