### ISSUE TITLE
glCreate* and glGen*

### ISSUE THREAD

**Issue by Drakoskai** [openglredbook/examples#4]
I noticed that many of your examples go back and forth between setting up using glGen and glCreate is there a preferred method?

**Comment by hutaocheng** [comment]
I also have this question. and tried to found the answer from the opengl 4.5 specification core, but failed

**Comment by grahamsellers** [comment]
My preference is to use glCreate*. It returns an initialized object and does not disturb OpenGL state. This is what I use in all new code. I updated many of the existing samples, but I suppose I missed a few. Perhaps I'll make another pass over the samples.

**Comment by Drakoskai** [comment]
Thanks for the response! I've had a lot of luck setting up buffers using the glCreate* with Java but in C++ the glCreate* methods often lead to program crashes while glGen* seems rock solid.  Some examples in C++ would be very helpful.  The Transform Feedback examples would probably be the most helpful, for me at least.
